[tool.poetry]
name = "clara"
version = "0.1.0"
description = "Agent Marketplace Platform"
authors = ["Your Name <you@example.com>"]

[tool.black]
line-length = 100
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 100
